#
# $$\    $$\           $$\                              
# $$ |   $$ |          $$ |                             
# $$ |   $$ |$$\   $$\ $$ | $$$$$$$\ $$$$$$\  $$$$$$$\  
# \$$\  $$  |$$ |  $$ |$$ |$$  _____|\____$$\ $$  __$$\ 
#  \$$\$$  / $$ |  $$ |$$ |$$ /      $$$$$$$ |$$ |  $$ |
#   \$$$  /  $$ |  $$ |$$ |$$ |     $$  __$$ |$$ |  $$ |
#    \$  /   \$$$$$$  |$$ |\$$$$$$$\\$$$$$$$ |$$ |  $$ |
#     \_/     \______/ \__| \_______|\_______|\__|  \__|                                                      
#                                            
# Vulcan 0.1
# By Astro Operations
# Discord: astrx.us/discord| Mustang#0001 | Daaz#0001
# Twitter: @AstroInDev
#

Messages:
  NoPermissions: "&cNo permission."
  NoPlayerFound: "&cNo online player with name: &e%player%"
  NoAbilityFound: "&cInvalid ability: &e%ability%&c, please try again."
  AbilityDisabled: "&cThat ability is currently disabled."
  Commands:
    Give:
      Sender: "&aYou has been given an item to %target%"
      Target: "&aYou have received an item from %sender%"
    ClearTimer:
      Sender: "&aYou have cleaned the %timer% cooldown of %target%"
      Target: "&a%sender% has cleaned your %timer% cooldown"
      NoHasCooldown: "&c%target% has no %timer% cooldown"
  Region:
    RegionCreate:
      AlreadyExist: "&4%name% &cregion already exist! "
      MakeASelection: "&cYou must set a WorldEdit selection."
      Created: "&aRegion &2%name% &asuccessfully created"
    RegionDelete:
      DoesNotExist: "&4%name% &cregion does not exist!"
      Deleted: "&aRegion &2%name% &asuccessfully deleted"
    OnAbilityUse: "&cYou can't use this ability on this region."
    OnTargetIsInRegion: "&c%target% is in protected region!"
  AbilitiesList:
    Status:
      Enabled: "&aEnabled"
      Disabled: "&cDisabled"
    Message:
      - "&7&m-------------------------------------------"
      - "&a&lAbilities List"
      - ""
      - "&fAntiFallBoots %antifallboots_status%"
      - "&fAntiTrap %antitrap_status%"
      - "&fAutoBow %autobow_status%"
      - "&fBedBomb %bedbomb_status%"
      - "&fBelchBomb %belchbomb_status%"
      - "&fCobweb %cobweb_status%"
      - "&fCocaine %cocaine_status%"
      - "&fCooldownBow %cooldownbow_status%"
      - "&fEffects %effects_status%"
      - "&fFireball %fireball_status%"
      - "&fFreeze %freeze_status%"
      - "&fFreeze Gun %freezegun_status%"
      - "&fGhost %ghost_status%"
      - "&fGrapplingHook %grapplinghook_status%"
      - "&fInventorySwitcher %inventoryswitcher_status%"
      - "&fNinja %ninja_status%"
      - "&fPearlReset %pearlreset_status%"
      - "&fPotionRefill %potionrefill_status%"
      - "&fRocketBoost %rocketboost_status%"
      - "&fStormBreaker %stormbreaker_status%"
      - "&fSwapperHelmet %swapperhelmet_status%"
      - "&fSwitcher %switcher_status%"
      - "&fViewSwitcher %viewswitcher_status%"
      - "&7&m-------------------------------------------"

###################
#  AntiFallBoots  #
###################

AntiFallBoots:
  Enabled: true
  Item:
    Material: 313
    Data: 0
    Name: "&6AntiFallBoots"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    RemoveOnUse: false

###################
#     AntiTrap    #
###################
AntiTrap:
  Enabled: true
  Item:
    Material: 399
    Data: 0
    Name: "&6AntiTrap"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 30
    RemoveOnUse: true
    Hits: 3
    DenyPlaceBlocks: true
    DenyBreakBlocks: true
    Time: 15
  Lang:
    OnExpire:
      - "&7Your &6AntiTrap &7cooldown has expired."
      - "&7You can use the antitrap again."
    OnCooldown:
      - "&cYou cannot use &6AntiTrap &cfor another &l%time%"
    Player:
      OnUse:
        - "&a%target% cannot place blocks for the next 15 seconds."
    Target:
      OnCooldown:
        - "&a%player% You cannot place blocks for the next 15 seconds!"
      OnPlaceBlock:
        - "&cYou can't place blocks right now!"
      OnBreakBlock:
        - "&cYou cannot break blocks right now!"
      OnOpenFence:
        - "&cYou cannot open &4Fence Gate&c right now!"
      OnOpenChest:
        - "&cYou cannot open &4Chest&c right now!"
###################
#     AutoBow     #
###################
AutoBow:
  Enabled: true
  Item:
    Name: "&6AutoBow"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 3
    RemoveOnUse: false
  Lang:
    OnExpire:
      - "&7Your &6AutoBow &7cooldown has expired."
      - "&7You can use the autobow again."
    OnCooldown:
      - "&cYou cannot use &6AutoBow &cfor another &l%time%"

###################
#     BedBomb     #
###################
BedBomb:
  Enabled: true
  Item:
    Name: "&6Bed Bomb"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 30
  Lang:
    OnExpire:
      - "&7Your &6Bed Bomb &7cooldown has expired."
      - "&7You can use the bed bomb again."
    OnCooldown:
      - "&cYou cannot use &6Bed Bomb &cfor another &l%time%"

###################
#    BelchBomb    #
###################
BelchBomb:
  Enabled: true
  Item:
    Material: 351
    Data: 0
    Name: "&6BelchBomb"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: true
    Radius: 20
    #<EFFECT>:<DURATION>:<AMPLIFIER>
    Effects:
      - "BLINDNESS:10:3"
  Lang:
    OnExpire:
      - "&7Your &6BelchBomb &7cooldown has expired."
      - "&7You can use the belchbomb again."
    OnCooldown:
      - "&cYou cannot use &6BelchBomb &cfor another &l%time%"
    Player:
      - "&aYou've used &6BelchBomb"
    Target:
      - "&a%player% have used &6BelchBomb"

###################
#     Cobweb      #
###################
Cobweb:
  Enabled: true
  Item:
    Material: 30
    Data: 0
    Name: "&6Cobweb"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: true
    DespawnTime: 30
  Lang:
    OnExpire:
      - "&7Your &6Cobweb &7cooldown has expired."
      - "&7You can use the cobweb again."
    OnCooldown:
      - "&cYou cannot use &6Cobweb &cfor another &l%time%"

###################
#     Cocaine     #
###################
Cocaine:
  Enabled: true
  Item:
    Material: 353
    Data: 0
    Name: "&6Cocaine"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: true
    #<EFFECT>:<DURATION>:<AMPLIFIER>
    Effects:
      - "SPEED:10:3"
  Lang:
    OnExpire:
      - "&7Your &6Cocaine &7cooldown has expired."
      - "&7You can use the cocaine again."
    OnCooldown:
      - "&cYou cannot use &6Cocaine &cfor another &l%time%"

###################
#   CooldownBow   #
###################
CooldownBow:
  Enabled: true
  Item:
    Name: "&6Cooldown Bow"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: true
    Command: "timer set Enderpearl %player% 16s"
  Lang:
    OnExpire:
      - "&7Your &6Cooldown Bow &7cooldown has expired."
      - "&7You can use the cooldown bow again."
    OnCooldown:
      - "&cYou cannot use &6Cooldown Bow &cfor another &l%time%"
    Player:
      - "&eYou've damaged &4&l%target% &ewith &6Cooldown Bow&e."
    Target:
      - "&eYou've been damaged by &4&l%player% &ewith &6Cooldown Bow"
      - "&eYou are now have enderpearl cooldown for 16 seconds."

###################
#     Effects     #
###################
Effects:
  Enabled: true
  Item:
    Type: Egg #Snowball, Egg
    Name: "&6Effects"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    #<EFFECT>:<DURATION>:<AMPLIFIER>
    Effects:
      - "SPEED:10:3"
  Lang:
    OnExpire:
      - "&7Your &6Effects &7cooldown has expired."
      - "&7You can use the effects again."
    OnCooldown:
      - "&cYou cannot use &6Effects &cfor another &l%time%"
    Player:
      - "&eYou've damaged &4&l%target% &ewith &6Effects&e."
    Target:
      - "&eYou've been damaged by &4&l%player% &ewith &6Effects&e."

###################
#     FireBall    #
###################
FireBall:
  Enabled: true
  Item:
    Material: 385
    Data: 0
    Name: "&6FireBall"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: true
  Lang:
    OnExpire:
      - "&7Your &6FireBall &7cooldown has expired."
      - "&7You can use the fireball again."
    OnCooldown:
      - "&cYou cannot use &6FireBall &cfor another &l%time%"

###################
#    FreezeGun    #
###################
FreezeGun:
  Enabled: true
  Item:
    Material: 293
    Data: 0
    Name: "&6Freeze Gun"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: false
    #<EFFECT>:<DURATION>:<AMPLIFIER>
    Effects:
      - "SLOW:6:4"
  Lang:
    OnExpire:
      - "&7Your &6Freeze Gun &7cooldown has expired."
      - "&7You can use the freeze gun again."
    OnCooldown:
      - "&cYou cannot use &6Freeze Gun &cfor another &l%time%"
    Player:
      - "&aYou has been freeze &2%target% &ausing &2Freeze gun"
    Target:
      - "&4%player% &chas been freeze you using &4Freeze Gun"

###################
# Grappling Hook  #
###################
GrapplingHook:
  Enabled: true
  Item:
    Name: "&6Grappling Hook"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
  Lang:
    OnExpire:
      - "&7Your &6Grappling Hook &7cooldown has expired."
      - "&7You can use the grappling hook again."
    OnCooldown:
      - "&cYou cannot use &6Grappling Hook &cfor another &l%time%"

###################
#      Ninja      #
###################
Ninja:
  Enabled: true
  Item:
    Material: 399
    Data: 0
    Name: "&6Ninja"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 30
    RemoveOnUse: true
    Range: 20
    TeleportCooldown: 5
  Lang:
    OnExpire:
      - "&7Your &6Ninja &7cooldown has expired."
      - "&7You can use the ninja again."
    OnCooldown:
      - "&cYou cannot use &6Ninja &cfor another &l%time%"
    Player:
      OnUse:
        - "&aYou will teleport to %target% in 5 seconds!"
      OnTeleport:
        - "&aYou've used &2Ninja &aand teleported to the &2%target% &aposition."
      OutOfRange:
        - "&c%target% is out of range!"
      NoTarget:
        - "&cYou dont have target to teleport"
    Target:
      OnPlayerUse:
        - "&4&l%player% &ehas used Ninja against you!"
      OnPlayerTeleport:
        - "&4%player% &chas teleported to your position using &4Ninja&c."
###################
#   Pearl Reset   #
###################
PearlReset:
  Enabled: true
  Item:
    Material: 351
    Data: 8
    Name: "&6Pearl Reset"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 30
    RemoveOnUse: true
    Command: "timer set Enderpearl %player% 0s"
  Lang:
    OnExpire:
      - "&7Your &6Pearl Reset &7cooldown has expired."
      - "&7You can use the pearl reset again."
    OnCooldown:
      - "&cYou cannot use &6Pearl Reset &cfor another &l%time%"

###################
#   RocketBoost   #
###################
RocketBoost:
  Enabled: true
  Item:
    Name: "&6RocketBoost"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: true
  Lang:
    OnExpire:
      - "&7Your &6RocketBoost &7cooldown has expired."
      - "&7You can use the rocketboost again."
    OnCooldown:
      - "&cYou cannot use &6RocketBoost &cfor another &l%time%"

###################
#   StormBreaker  #
###################
StormBreaker:
  Enabled: true
  Item:
    Material: 279
    Data: 0
    Name: "&6StormBreaker"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: false
    Radius: 20
  Lang:
    OnExpire:
      - "&7Your &6StormBreaker &7cooldown has expired."
      - "&7You can use the stormbreaker again."
    OnCooldown:
      - "&cYou cannot use &6StormBreaker &cfor another &l%time%"

###################
#  SwapperHelmet  #
###################
SwapperHelmet:
  Enabled: true
  Item:
    Material: 286
    Data: 0
    Name: "&6SwapperHelmet"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 30
    Delay: 3
    OnlyDiamondHelmet: true
  Lang:
    OnExpire:
      - "&7Your &6SwapperHelmet &7cooldown has expired."
      - "&7You can use the swapperhelmet again."
    OnCooldown:
      - "&cYou cannot use &6SwapperHelmet &cfor another &l%time%"
    Player:
      OnUse:
        - "&aYou have used your &2&lSwapperHelmet"
        - "&a%target% will lose their helmet in 3 seconds!"
      NoDiamondHelmet: "&c%target% is not wearing a diamond helmet!"
    Target:
      OnDamage:
        - "&aYou have hit with the &2&lSwapperHelmet"
        - "&aYou will lose your helmet in 3 seconds!"
      FullInventory: "&4Your inventory is full, your helmet is on the ground!"

###################
#    Switcher     #
###################
Switcher:
  Enabled: true
  Item:
    Type: Snowball #Snowball, Egg
    Name: "&6Switcher"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    Range: 15 #In Blocks
  Lang:
    OnExpire:
      - "&7Your &6Switcher &7cooldown has expired."
      - "&7You can use the switcher again."
    OnCooldown:
      - "&cYou cannot use &6Switcher &cfor another &l%time%"
    Player:
      - "&eYou've damaged &4&l%target% &ewith &6Switcher&e."
    Target:
      - "&eYou've been damaged by &4&l%player% &ewith &6Switcher&e."
###################
#  ViewSwitcher   #
###################
ViewSwitcher:
  Enabled: true
  Item:
    Material: 280
    Data: 0
    Name: "&6ViewSwitcher"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 16
    RemoveOnUse: false
    Rotate:
      Yaw: 180
      Pitch: 0
  Lang:
    OnExpire:
      - "&7Your &6ViewSwitcher &7cooldown has expired."
      - "&7You can use the viewswitcher again."
    OnCooldown:
      - "&cYou cannot use &6ViewSwitcher &cfor another &l%time%"
###################
#      Ghost      #
###################
Ghost:
  Enabled: true
  Item:
    Material: 351
    Data: 7
    Name: "&6Ghost"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 240
    RemoveOnUse: true
    Duration: 30
  Lang:
    OnExpire:
      - "&7Your &6Ghost &7cooldown has expired."
      - "&7You can use the ghost again."
    OnCooldown:
      - "&cYou cannot use &6Ghost &cfor another &l%time%"
    Player:
      OnAttack:
        - "&cYour Ghost mode has been removed"
      OnDamage:
        - "&4%target% &chas removed your Ghost mode."
    Target:
      OnAttack:
        - "&aYour removed the Ghost mode of &2%player%"
###################
#      Freeze     #
###################
Freeze:
  Enabled: true
  Item:
    Material: 79
    Data: 0
    Name: "&6Freeze"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 30
    RemoveOnUse: true
    Radius: 5
    #<EFFECT>:<DURATION>:<AMPLIFIER>
    Effects:
      - "SLOW:6:3"
  Lang:
    OnExpire:
      - "&7Your &6Freeze &7cooldown has expired."
      - "&7You can use the frezee again."
    OnCooldown:
      - "&cYou cannot use &6Freeze &cfor another &l%time%"
    Player:
      - "&aYou has been use &2Freeze"
    Target:
      - "&4%player% &chas been freeze you using &4Freeze Ability"
#####################
# InventorySwitcher #
#####################
InventorySwitcher:
  Enabled: true
  Item:
    Material: 352
    Data: 0
    Name: "&6InventorySwitcher"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 240
    RemoveOnUse: true
  Lang:
    OnExpire:
      - "&7Your &6InventorySwitcher &7cooldown has expired."
      - "&7You can use the inventoryswitcher again."
    OnCooldown:
      - "&cYou cannot use &6InventorySwitcher &cfor another &l%time%"
    Player:
      - "You Has Been Use InventorySwitcher with %target%"
    Target:
      - "&4%player% &chas been use InventorySwitcher with you!"
      - "&cYour hotbar has been switch!"
###################
#  PotionRefill   #
###################
PotionRefill:
  Enabled: true
  Item:
    Material: 379
    Data: 0
    Name: "&6Refill"
    Lore:
      - "&7&m-------------------------------------------"
      - "&fPlease change this description in config.yml"
      - "&7&m-------------------------------------------"
  Options:
    Cooldown: 240
    RemoveOnUse: true
  Lang:
    OnExpire:
      - "&7Your &6Refill &7cooldown has expired."
      - "&7You can use the refill again."
    OnCooldown:
      - "&cYou cannot use &6Refill &cfor another &l%time%"
    OnUse:
      - "&aYou has been use PotionRefill"
      - "&dSplash Potion of Healing &ahas been added to your inventory"
    FullInventory:
      - "&cYour inventory is full"